#!/bin/bash
git reset --hard origin/master
git pull
git submodule update --init --recursive
git submodule init
git submodule update
git submodule foreach git checkout master
git submodule foreach git pull